StatusGizi.Web/Controllers/KelurahanController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using StatusGizi.Domain.Entities;
using StatusGizi.Domain.Enums;
using StatusGizi.Infrastructure.Database;
using StatusGizi.Web.Models;
using StatusGizi.Web.Models.KelurahanModels;
using StatusGizi.Web.Services.Contracts;
using System.Data;

namespace StatusGizi.Web.Controllers;

public class KelurahanController : Controller
{
    private readonly AppDbContext _appDbContext;
    private readonly IToastrNotificationService _notificationService;

    public KelurahanController(AppDbContext appDbContext, IToastrNotificationService notificationService)
    {
        _appDbContext = appDbContext;
        _notificationService = notificationService;
    }

    public async Task<IActionResult> Index()
    {
        var vm = await _appDbContext.TblDesaKelurahan
            .Include(p => p.DaftarPosyandu).ThenInclude(p => p.DaftarPengecekan)
            .ToListAsync();

        return View(vm);
    }

    [Authorize(Roles = AppUserRoles.Kader)]
    public async Task<IActionResult> Detail(int id)
    {
        var desaKelurahan = await _appDbContext.TblDesaKelurahan
            .FirstOrDefaultAsync(d => d.Id == id);

        if (desaKelurahan is null) return NotFound();

        var daftarPengecekan = await _appDbContext.TblPengecekan
            .Include(p => p.Balita).ThenInclude(b => b.OrangTua).ThenInclude(o => o.DesaKelurahan)
            .Include(p => p.Posyandu).ThenInclude(p => p.DesaKelurahan)
            .Where(p => p.Posyandu.DesaKelurahan.Id == desaKelurahan.Id)
            .ToListAsync();

        return View(new DetailVM
        {
            DesaKelurahan = desaKelurahan,
            DaftarPengecekan = daftarPengecekan,
        });
    }

    [Authorize(Roles = AppUserRoles.Kader)]
    public IActionResult Tambah()
    {
        return View(new TambahVM());
    }

    [Authorize(Roles = AppUserRoles.Kader)]
    [HttpPost]
    public async Task<IActionResult> Tambah(TambahVM vm)
    {
        if (!ModelState.IsValid) return View(vm);

        if(await _appDbContext.TblDesaKelurahan.AnyAsync(d => d.Nama == vm.Nama))
        {
            ModelState.AddModelError(nameof(TambahVM.Nama), $"Nama '{vm.Nama}' sudah digunakan");
            return View(vm);
        }

        var desaKelurahan = new DesaKelurahan
        {
            Nama = vm.Nama
        };
        _appDbContext.TblDesaKelurahan.Add(desaKelurahan);
        try
        {
            await _appDbContext.SaveChangesAsync();
        }
        catch (Exception)
        {
            ModelState.AddModelError(string.Empty, "Terjadi masalah saat mencoba menyimpan");
            return View(vm);
        }

        _notificationService.AddNotification(new ToastrNotification
        {
            Type = ToastrNotificationType.Success,
            Title = "Kelurahan Berhasil DiTambahkan!"
        });

        return RedirectToAction(nameof(Detail), new { id = desaKelurahan.Id });
    }
}

StatusGizi.Web/Controllers/PemeriksaanController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using StatusGizi.Domain.Entities;
using StatusGizi.Domain.Enums;
using StatusGizi.Infrastructure.Database;
using StatusGizi.Web.Models.PemeriksaanModels;

namespace StatusGizi.Web.Controllers;

[Authorize(Roles = AppUserRoles.Kader)]
public class PemeriksaanController : Controller
{
    private readonly AppDbContext _appDbContext;

    public PemeriksaanController(AppDbContext appDbContext)
    {
        _appDbContext = appDbContext;
    }

    public async Task<IActionResult> Index(int id)
    {
        var pengecekan = await _appDbContext
            .TblPengecekan
            .Include(p => p.Balita).ThenInclude(b => b.OrangTua).ThenInclude(o => o.DesaKelurahan)
            .Include(p => p.Posyandu).ThenInclude(p => p.DesaKelurahan)
            .FirstOrDefaultAsync(p => p.Id == id);

        if (pengecekan is null) return NotFound();

        var kategoriUmur = pengecekan.UsiaDalamBulan <= 24 ? KategoriUmur.BulanBawah24 : KategoriUmur.Bulan24Sampai60;

        var standarBeratMenurutBBTB = await _appDbContext
            .TblStandarBeratMenurutBBTB
            .Where(s => s.JenisKelamin == pengecekan.Balita.JenisKelamin && s.KategoriUmur == kategoriUmur && s.TinggiBadan <= pengecekan.TinggiBadan)
            .OrderBy(s => s.TinggiBadan)
            .LastOrDefaultAsync();

        if (standarBeratMenurutBBTB is null) return BadRequest();

        return View(new IndexVM { StandarBeratMenurutBBTB = standarBeratMenurutBBTB, Pengecekan = pengecekan });
    }

    public IActionResult Tambah()
    {
        return View(new TambahVM { TanggalUkur = DateOnly.FromDateTime(DateTime.Now)});
    }

    [HttpPost]
    public async Task<IActionResult> Tambah(TambahVM vm)
    {
        if (!ModelState.IsValid) return View(vm);

        var balita = await _appDbContext.TblBalita.FirstOrDefaultAsync(b => b.NIK == vm.NIK);
        if (balita is null)
        {
            ModelState.AddModelError(nameof(TambahVM.NIK), "Balita tidak ditemukan");
            return View(vm);
        }

        var posyandu = await _appDbContext.TblPosyandu.FirstOrDefaultAsync(p => p.Id == vm.PosyanduId);
        if (posyandu is null)
        {
            ModelState.AddModelError(nameof(TambahVM.PosyanduId), "Posyandu tidak ditemukan");
            return View(vm);
        }

        var pengecekan = new Pengecekan
        {
            Balita = balita,
            Posyandu = posyandu,
            LingkarLenganAtas = vm.LingkarLenganAtas,
            BeratBadan = vm.BeratBadan,
            TanggalPengecekan = vm.TanggalUkur,
            TinggiBadan = vm.TinggiBadan,
        };

        var kategoriUmur = pengecekan.UsiaDalamBulan <= 24 ? KategoriUmur.BulanBawah24 : KategoriUmur.Bulan24Sampai60;
        var standarBeratMenurutBBTB = await _appDbContext
            .TblStandarBeratMenurutBBTB
            .Where(s => s.JenisKelamin == pengecekan.Balita.JenisKelamin && s.KategoriUmur == kategoriUmur && s.TinggiBadan <= pengecekan.TinggiBadan)
            .OrderBy(s => s.TinggiBadan)
            .LastOrDefaultAsync();

        if (standarBeratMenurutBBTB is null) return BadRequest();

        if (pengecekan.BeratBadan < standarBeratMenurutBBTB.SDMinus3)
        {
            pengecekan.KategoriGizi = KategoriGizi.GiziBuruk;
        }
        else if (pengecekan.BeratBadan >= standarBeratMenurutBBTB.SDMinus3 && pengecekan.BeratBadan < standarBeratMenurutBBTB.SDMinus2)
        {
            pengecekan.KategoriGizi = KategoriGizi.GiziKurang;
        }
        else if (pengecekan.BeratBadan >= standarBeratMenurutBBTB.SDMinus2 && pengecekan.BeratBadan <= standarBeratMenurutBBTB.SDPlus1)
        {
            pengecekan.KategoriGizi = KategoriGizi.GiziBaik;
        }
        else if (pengecekan.BeratBadan > standarBeratMenurutBBTB.SDPlus1 && pengecekan.BeratBadan <= standarBeratMenurutBBTB.SDPlus2)
        {
            pengecekan.KategoriGizi = KategoriGizi.BerpotensiBerlebih;
        }
        else if (pengecekan.BeratBadan > standarBeratMenurutBBTB.SDPlus2 && pengecekan.BeratBadan <= standarBeratMenurutBBTB.SDPlus3)
        {
            pengecekan.KategoriGizi = KategoriGizi.GiziBerlebih;
        }
        else
        {
            pengecekan.KategoriGizi = KategoriGizi.Obesitas;
        }

        _appDbContext.TblPengecekan.Add(pengecekan);

        try
        {
            await _appDbContext.SaveChangesAsync();
        }
        catch (Exception)
        {
            ModelState.AddModelError(string.Empty, "Terjadi error saat menyimpan data ke database");
            return View(vm);
        }

        return RedirectToAction(nameof(Index), new { id = pengecekan.Id });
    }
}

StatusGizi.Web/ViewComponents/ChartViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using StatusGizi.Web.Models;

namespace StatusGizi.Web.ViewComponents;

public class ChartViewComponent : ViewComponent
{
    public IViewComponentResult Invoke(ChartVM chartModel)
    {
        return View(chartModel);
    }
}

StatusGizi.Web/Views/Kelurahan/Detail.cshtml
@using Humanizer
@using Humanizer.Localisation

@model DetailVM

@{
    ViewData["Title"] = "Detail";
    var cultureInfo = new CultureInfo("id-ID");
}

<style>
    .table {
        font-size: 0.7em;
    }

    .table .btn {
        font-size: 0.7em;
    }
</style>

<h1>Desa : @Model.DesaKelurahan.Nama</h1>

<div class="row">
    <div class="col-md-8">
        <table class="table dataTable">
            <thead>
                <tr>
                    <th>No</th>
                    <th>NIK</th>
                    <th>Nama</th>
                    <th>Posyandu</th>
                    <th>Tgl Ukur</th>
                    <th>Usia Saat Ukur</th>
                    <th>Berat Badan</th>
                    <th>Tinggi Badan</th>
                    <th>Kategori Gizi (BB/TB)</th>
                    <th>Aksi</th>
                </tr>
            </thead>
            <tbody>
                @{
                    var no = 1;
                }
                @foreach (var pengecekan in Model.DaftarPengecekan)
                {
                    <tr>
                        <td>@no</td>
                        <td>@pengecekan.Balita.NIK</td>
                        <td>@pengecekan.Balita.Nama</td>
                        <td>@pengecekan.Posyandu.Nama</td>
                        <td>@pengecekan.TanggalPengecekan.ToString(cultureInfo.DateTimeFormat.ShortDatePattern, cultureInfo)</td>
                        <td>@pengecekan.Usia.Humanize(7, countEmptyUnits: true, culture: cultureInfo, maxUnit: TimeUnit.Year, minUnit: TimeUnit.Day, collectionSeparator: " ")</td>
                        <td>@pengecekan.BeratBadan Kg</td>
                        <td>@pengecekan.TinggiBadan cm</td>
                        <td>@pengecekan.KategoriGizi.Humanize()</td>
                        <td>
                            <a asp-action="Index" asp-controller="Pemeriksaan" asp-route-id="@pengecekan.Id" class="btn btn-primary">Detail</a>
                        </td>
                    </tr>
                    no++;
                }
            </tbody>
        </table>
    </div>
    <div class="col-md-4">
        <div class="card">
            <div class="card-header">
                Distribusi Kategori Gizi Balita di Desa @Model.DesaKelurahan.Nama
            </div>
            <div class="card-body">
                @{
                    var chartVM = new ChartVM
                    {
                        Label = $"Jumlah",
                        Type = ChartType.Pie,
                        Data = new Dictionary<string, double>(Model.DaftarPengecekan.GroupBy(p => p.KategoriGizi).OrderBy(g => g.Key).Select(g => new KeyValuePair<string, double>(g.Key.Humanize(), g.Count()))),
                    };
                }
                <vc:chart chart-model=chartVM />
            </div>
        </div>
    </div>
</div>

StatusGizi.Web/Views/Kelurahan/Index.cshtml
@using StatusGizi.Web.Authentication
@inject ISignInManager SignInManager

@model List<DesaKelurahan>

@{
    ViewData["Title"] = "Kelurahan";
    var user = await SignInManager.GetUser();
}

<style>
    .table {
        font-size: 0.6em;
    }

        .table .btn {
            font-size: 0.6em;
        }
</style>


@if (user is not null && user.Role == AppUserRoles.Kader)
{
    <div class="row mb-3">
        <div class="col">
            <a asp-action="@nameof(KelurahanController.Tambah)" class="btn btn-primary">Tambah</a>
        </div>
    </div>
}
<div class="row">
    <div class="col-md-6">
        <table class="table dataTable">
            <thead>
                <tr>
                    <th>Desa/Kelurahan</th>
                    @foreach (var kategoriGizi in Enum.GetValues<KategoriGizi>())
                    {
                        <th>@kategoriGizi.Humanize()</th>
                    }
                    <th>Sub Total</th>
                    @if (user is not null && user.Role == AppUserRoles.Kader)
                    {
                        <th>Aksi</th>
                    }
                </tr>
            </thead>
            <tbody>
                @foreach (var kelurahan in Model)
                {
                    var daftarPengecekan = kelurahan.DaftarPosyandu.SelectMany(p => p.DaftarPengecekan);
                    var grouping = daftarPengecekan.GroupBy(p => p.KategoriGizi);
                    <tr>
                        <th>@kelurahan.Nama</th>
                        <td>@(grouping.FirstOrDefault(g => g.Key == KategoriGizi.GiziBuruk)?.Count() ?? 0)</td>
                        <td>@(grouping.FirstOrDefault(g => g.Key == KategoriGizi.GiziKurang)?.Count() ?? 0)</td>
                        <td>@(grouping.FirstOrDefault(g => g.Key == KategoriGizi.GiziBaik)?.Count() ?? 0)</td>
                        <td>@(grouping.FirstOrDefault(g => g.Key == KategoriGizi.BerpotensiBerlebih)?.Count() ?? 0)</td>
                        <td>@(grouping.FirstOrDefault(g => g.Key == KategoriGizi.GiziBerlebih)?.Count() ?? 0)</td>
                        <td>@(grouping.FirstOrDefault(g => g.Key == KategoriGizi.Obesitas)?.Count() ?? 0)</td>
                        <td>@(daftarPengecekan.Count())</td>
                        @if (user is not null && user.Role == AppUserRoles.Kader)
                        {
                            <td>
                                <a asp-action="Detail" asp-route-id="@kelurahan.Id" class="btn btn-primary">Detail</a>
                            </td>
                        }
                    </tr>
                }
            </tbody>
            <tfoot>
                <tr>
                    @{
                        var daftarPengecekanSemua = Model.SelectMany(k => k.DaftarPosyandu.SelectMany(p => p.DaftarPengecekan));
                    }
                    <th>Total</th>
                    <td>@(daftarPengecekanSemua.Where(p => p.KategoriGizi == KategoriGizi.GiziBuruk).Count())</td>
                    <td>@(daftarPengecekanSemua.Where(p => p.KategoriGizi == KategoriGizi.GiziKurang).Count())</td>
                    <td>@(daftarPengecekanSemua.Where(p => p.KategoriGizi == KategoriGizi.GiziBaik).Count())</td>
                    <td>@(daftarPengecekanSemua.Where(p => p.KategoriGizi == KategoriGizi.BerpotensiBerlebih).Count())</td>
                    <td>@(daftarPengecekanSemua.Where(p => p.KategoriGizi == KategoriGizi.GiziBerlebih).Count())</td>
                    <td>@(daftarPengecekanSemua.Where(p => p.KategoriGizi == KategoriGizi.Obesitas).Count())</td>
                    <td>@(daftarPengecekanSemua.Count())</td>
                    @if (user is not null && user.Role == AppUserRoles.Kader)
                    {
                        <td> </td>
                    }
                </tr>
            </tfoot>
        </table>
    </div>
    <div class="col-md-6">
        <div class="owl-carousel owl-theme grafikContainer">
            @foreach (var kategoriGizi in Enum.GetValues<KategoriGizi>())
            {
                <div class="row">
                    <div class="card">
                        <div class="card-header">
                            Jumlah Balita @kategoriGizi.Humanize()
                        </div>
                        <div class="card-body">
                            <vc:chart chart-model=@(new ChartVM { Label = $"Jumlah Balita {kategoriGizi.Humanize()}", Type = ChartType.Bar, Data = new Dictionary<string, double>(Model.Select(k => new KeyValuePair<string, double>(k.Nama, k.DaftarPosyandu.SelectMany(p => p.DaftarPengecekan).Where(p => p.KategoriGizi == kategoriGizi).Count())))}) />
                        </div>
                    </div>
                </div>
            }
        </div>
    </div>
</div>

@section Scripts {
    <script type="text/javascript">
        $(function () {
            $('.grafikContainer').owlCarousel({
                loop: false,
                autoPlay: false,
                nav: false,
                items: 1
            });
        });
    </script>
}

StatusGizi.Web/Views/Kelurahan/Tambah.cshtml
@model TambahVM

@{
    ViewData["Title"] = "Kelurahan | Tambah";
}

<form asp-action="@nameof(KelurahanController.Tambah)">
    <div class="card">
        <div class="card-header">
            <h3>Tambah Kelurahan</h3>
        </div>
        <div class="card-body">
            <div asp-validation-summary="ModelOnly" class="form-text text-danger"></div>

            <div class="col mb-3">
                <label asp-for="@Model.Nama" class="form-label"></label>
                <input asp-for="@Model.Nama" class="form-control" />
                <span asp-validation-for="@Model.Nama" class="form-text text-danger"></span>
            </div>

        </div>
        <div class="card-footer">
            <div class="col">
                <button class="btn btn-primary me-2">Simpan</button>
                <button class="btn btn-danger">Batal</button>
            </div>
        </div>
    </div>
</form>

@section Scripts {
    <partial name="_ValidationScriptsPartial" />
}