StatusGizi.Web/Controllers/BalitaController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using StatusGizi.Domain.Entities;
using StatusGizi.Infrastructure.Database;
using StatusGizi.Web.Models.BalitaModels;
using StatusGizi.Web.Services.Contracts;

namespace StatusGizi.Web.Controllers;

[Authorize(Roles = AppUserRoles.Kader)]
public class BalitaController : Controller
{
    private readonly AppDbContext _appDbContext;
    private readonly IToastrNotificationService _notificationService;

    public BalitaController(AppDbContext appDbContext, IToastrNotificationService notificationService)
    {
        _appDbContext = appDbContext;
        _notificationService = notificationService;
    }

    public async Task<IActionResult> Index()
    {
        var daftarBalita = await _appDbContext.TblBalita
            .Include(b => b.OrangTua).ThenInclude(o => o.DesaKelurahan)
            .Include(b => b.DaftarPengecekan).ThenInclude(p => p.Posyandu).ThenInclude(p => p.DesaKelurahan)
            .ToListAsync();

        return View(daftarBalita);
    }

    public async Task<IActionResult> Detail(string id)
    {
        var balita = await _appDbContext.TblBalita
            .Include(b => b.OrangTua).ThenInclude(o => o.DesaKelurahan)
            .Include(b => b.DaftarPengecekan).ThenInclude(p => p.Posyandu).ThenInclude(p => p.DesaKelurahan)
            .FirstOrDefaultAsync(b => b.NIK == id);

        if (balita is null) return NotFound();

        return View(balita);
    }

    public IActionResult Tambah() => View(new TambahVM());

    [HttpPost]
    public async Task<IActionResult> Tambah(TambahVM vm)
    {
        if (!ModelState.IsValid) return View(vm);

        if(await _appDbContext.TblBalita.AnyAsync(b => b.NIK == vm.NIK))
        {
            ModelState.AddModelError(nameof(TambahVM.NIK), $"NIK '{vm.NIK}' dimiliki oleh balita lain");
            return View(vm);
        }

        var orangTua = await _appDbContext.TblOrangTua.FirstOrDefaultAsync(o => o.Id == vm.OrangTuaId);
        if(orangTua is null)
        {
            ModelState.AddModelError(nameof(TambahVM.OrangTuaId), "Orang Tua tidak ditemukan");
            return View(vm);
        }

        var balita = new Balita
        {
            NIK = vm.NIK,
            Nama = vm.Nama,
            JenisKelamin = vm.JenisKelamin,
            BeratBadanWaktuLahir = vm.BeratBadanLahir,
            TinggiBadanWaktuLahir = vm.TinggiBadanLahir,
            TanggalLahir = vm.TanggalLahir,
            OrangTua = orangTua
        };

        _appDbContext.TblBalita.Add(balita);

        try
        {
            await _appDbContext.SaveChangesAsync();
        }
        catch (Exception)
        {
            ModelState.AddModelError(string.Empty, "Terjadi kesalahan saat mencoba menyimpan perubahan");
            return View(vm);
        }

        _notificationService.AddSuccess("Balita berhasil ditambahkan");

        return RedirectToAction(nameof(Detail), new { id = balita.NIK });
    }
}

StatusGizi.Web/Controllers/KelurahanController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using StatusGizi.Domain.Entities;
using StatusGizi.Domain.Enums;
using StatusGizi.Infrastructure.Database;
using StatusGizi.Web.Models;
using StatusGizi.Web.Models.KelurahanModels;
using StatusGizi.Web.Services.Contracts;
using System.Data;

namespace StatusGizi.Web.Controllers;

public class KelurahanController : Controller
{
    private readonly AppDbContext _appDbContext;
    private readonly IToastrNotificationService _notificationService;

    public KelurahanController(AppDbContext appDbContext, IToastrNotificationService notificationService)
    {
        _appDbContext = appDbContext;
        _notificationService = notificationService;
    }

    public async Task<IActionResult> Index()
    {
        var vm = await _appDbContext.TblDesaKelurahan
            .Include(p => p.DaftarPosyandu).ThenInclude(p => p.DaftarPengecekan)
            .ToListAsync();

        return View(vm);
    }

    [Authorize(Roles = AppUserRoles.Kader)]
    public async Task<IActionResult> Detail(int id)
    {
        var desaKelurahan = await _appDbContext.TblDesaKelurahan
            .FirstOrDefaultAsync(d => d.Id == id);

        if (desaKelurahan is null) return NotFound();

        var daftarPengecekan = await _appDbContext.TblPengecekan
            .Include(p => p.Balita).ThenInclude(b => b.OrangTua).ThenInclude(o => o.DesaKelurahan)
            .Include(p => p.Posyandu).ThenInclude(p => p.DesaKelurahan)
            .Where(p => p.Posyandu.DesaKelurahan.Id == desaKelurahan.Id)
            .ToListAsync();

        return View(new DetailVM
        {
            DesaKelurahan = desaKelurahan,
            DaftarPengecekan = daftarPengecekan,
        });
    }

    [Authorize(Roles = AppUserRoles.Kader)]
    public IActionResult Tambah()
    {
        return View(new TambahVM());
    }

    [Authorize(Roles = AppUserRoles.Kader)]
    [HttpPost]
    public async Task<IActionResult> Tambah(TambahVM vm)
    {
        if (!ModelState.IsValid) return View(vm);

        if(await _appDbContext.TblDesaKelurahan.AnyAsync(d => d.Nama == vm.Nama))
        {
            ModelState.AddModelError(nameof(TambahVM.Nama), $"Nama '{vm.Nama}' sudah digunakan");
            return View(vm);
        }

        var desaKelurahan = new DesaKelurahan
        {
            Nama = vm.Nama
        };
        _appDbContext.TblDesaKelurahan.Add(desaKelurahan);
        try
        {
            await _appDbContext.SaveChangesAsync();
        }
        catch (Exception)
        {
            ModelState.AddModelError(string.Empty, "Terjadi masalah saat mencoba menyimpan");
            return View(vm);
        }

        _notificationService.AddNotification(new ToastrNotification
        {
            Type = ToastrNotificationType.Success,
            Title = "Kelurahan Berhasil DiTambahkan!"
        });

        return RedirectToAction(nameof(Detail), new { id = desaKelurahan.Id });
    }
}

StatusGizi.Web/Controllers/OrangTuaController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using StatusGizi.Domain.Entities;
using StatusGizi.Infrastructure.Database;
using StatusGizi.Web.Models.OrangTuaModels;
using StatusGizi.Web.Services.Contracts;

namespace StatusGizi.Web.Controllers;

[Authorize(Roles = AppUserRoles.Kader)]
public class OrangTuaController : Controller
{
    private readonly AppDbContext _appDbContext;
    private readonly IPasswordHasher<AppUser> _passwordHasher;
    private readonly IToastrNotificationService _notificationService;

    public OrangTuaController(
        AppDbContext appDbContext,
        IPasswordHasher<AppUser> passwordHasher,
        IToastrNotificationService notificationService)
    {
        _appDbContext = appDbContext;
        _passwordHasher = passwordHasher;
        _notificationService = notificationService;
    }

    public async Task<IActionResult> Index()
    {
        var daftarOrangTua = await _appDbContext.TblOrangTua
            .Include(o => o.DesaKelurahan)
            .Include(o => o.DaftarBalita)
            .ToListAsync();

        return View(daftarOrangTua);
    }

    public async Task<IActionResult> Detail(int id)
    {
        var orangTua = await _appDbContext.TblOrangTua
            .Include(o => o.DesaKelurahan)
            .Include(o => o.DaftarBalita).ThenInclude(b => b.DaftarPengecekan).ThenInclude(p => p.Posyandu)
            .FirstOrDefaultAsync(o => o.Id == id);

        if (orangTua is null) return NotFound();

        return View(orangTua);
    }

    public IActionResult Tambah() => View(new TambahVM());

    [HttpPost]
    public async Task<IActionResult> Tambah(TambahVM vm)
    {
        if(!ModelState.IsValid) return View(vm);

        var desaKelurahan = await _appDbContext.TblDesaKelurahan
            .Include(k => k.DaftarOrangTua)
            .FirstOrDefaultAsync(k => k.Id == vm.DesaKelurahanId);

        if(desaKelurahan is null)
        {
            ModelState.AddModelError(nameof(TambahVM.DesaKelurahanId), "Desa/Kelurahan tidak ditemukan");
            return View(vm);
        }

        var orangTua = new OrangTua
        {
            Nama = vm.Nama,
            DesaKelurahan = desaKelurahan
        };

        var appUser = new AppUser
        {
            UserName = orangTua.Nama.ToLower().Split(" ").First(),
            PasswordHash = _passwordHasher.HashPassword(null, "password"),
            OrangTua = orangTua,
            Role = AppUserRoles.OrangTua
        };

        _appDbContext.TblOrangTua.Add(orangTua);
        _appDbContext.TblAppUser.Add(appUser);

        try
        {
            await _appDbContext.SaveChangesAsync();
        }
        catch (Exception)
        {
            ModelState.AddModelError(string.Empty, "Terjadi kesalahan saat mencoba menyimpan perubahan");
            return View(vm);
        }

        _notificationService.AddSuccess("Orang Tua berhasil ditambahkan");

        return RedirectToAction(nameof(Detail), new { id = orangTua.Id });
    }
}

StatusGizi.Web/Controllers/PosyanduController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using StatusGizi.Domain.Entities;
using StatusGizi.Infrastructure.Database;
using StatusGizi.Web.Models.PosyanduModels;
using StatusGizi.Web.Services.Contracts;

namespace StatusGizi.Web.Controllers;

public class PosyanduController : Controller
{
    private readonly AppDbContext _appDbContext;
    private readonly IToastrNotificationService _notificationService;

    public PosyanduController(AppDbContext appDbContext, IToastrNotificationService notificationService)
    {
        _appDbContext = appDbContext;
        _notificationService = notificationService;
    }

    public async Task<IActionResult> Index()
    {
        var vm = await _appDbContext.TblPosyandu
            .Include(p => p.DaftarPengecekan)
            .ToListAsync();

        return View(vm);
    }

    [Authorize(Roles = AppUserRoles.Kader)]
    public async Task<IActionResult> Detail(int id)
    {
        var posyandu = await _appDbContext.TblPosyandu
            .Include(p => p.DaftarPengecekan).ThenInclude(p => p.Balita)
            .FirstOrDefaultAsync(p => p.Id == id);

        if (posyandu is null) return NotFound();

        return View(posyandu);
    }

    [Authorize(Roles = AppUserRoles.Kader)]
    public IActionResult Tambah() => View(new TambahVM());

    [HttpPost]
    [Authorize(Roles = AppUserRoles.Kader)]
    public async Task<IActionResult> Tambah(TambahVM vm)
    {
        if(!ModelState.IsValid) return View(vm);

        var desaKelurahan = await _appDbContext.TblDesaKelurahan
            .Include(d => d.DaftarPosyandu)
            .FirstOrDefaultAsync(d => d.Id == vm.DesaKelurahanId);

        if(desaKelurahan is null)
        {
            ModelState.AddModelError(nameof(TambahVM.DesaKelurahanId), "Desa/Kelurahan tidak ditemukan");
            return View(vm);
        }

        if(desaKelurahan.DaftarPosyandu.Any(p => p.Nama == vm.Nama))
        {
            ModelState.AddModelError(nameof(TambahVM.Nama),
                $"Nama posyandu '{vm.Nama}' sudah digunakan posyandu lain di {desaKelurahan.Nama}");
            return View(vm);
        }

        var posyandu = new Posyandu
        {
            Nama = vm.Nama,
            DesaKelurahan = desaKelurahan
        };
        _appDbContext.TblPosyandu.Add(posyandu);

        try
        {
            await _appDbContext.SaveChangesAsync();
        }
        catch (Exception)
        {
            ModelState.AddModelError(string.Empty, "Terjadi kesalahan saat mencoba menyimpan perubahan");
            return View(vm);
        }

        _notificationService.AddSuccess("Posyandu berhasil ditambahkan");

        return RedirectToAction(nameof(Index));
    }
}

StatusGizi.Web/Views/Shared/_Layout.cshtml
@using StatusGizi.Web.Authentication
@inject ISignInManager SignInManager

@{
    var user = await SignInManager.GetUser();
}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - SI Status Gizi</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />

    <link href="~/lib/datatables/css/jquery.dataTables.min.css" rel="stylesheet" asp-append-version="true" />

    @* Responsive *@
    <link href="~/lib/datatables/responsive-2.5.0/css/responsive.bootstrap.css" rel="stylesheet" />
    <link href="~/lib/datatables/responsive-2.5.0/css/responsive.bootstrap4.css" rel="stylesheet" />
    <link href="~/lib/datatables/responsive-2.5.0/css/responsive.datatables.css" rel="stylesheet" />
    <link href="~/lib/datatables/responsive-2.5.0/css/responsive.jqueryui.css" rel="stylesheet" />
    @* Responsive *@

    <!-- Inisialisasi Owl Carousel -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/OwlCarousel2/2.3.4/assets/owl.carousel.min.css" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/OwlCarousel2/2.3.4/assets/owl.theme.default.min.css" />
    <!-- Akhir Inisialisasi Owl Carousel -->

    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/StatusGizi.Web.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">SI Status Gizi</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home </a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Kelurahan" asp-action="Index">Kelurahan</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Posyandu" asp-action="Index">Posyandu</a>
                        </li>
                        @if (user is not null && user.Role == AppUserRoles.Kader)
                        {
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="OrangTua" asp-action="Index">Orang Tua</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Balita" asp-action="Index">Balita</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Pemeriksaan" asp-action="Tambah">Tambah Data Pemeriksaan</a>
                            </li>
                        }

                        @if (user is null)
                        {
                            <li class="nav-item ms-auto me-3">
                                <a class="nav-link text-dark btn" asp-area="" asp-controller="Home" asp-action="Login">Masuk</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-light btn btn-primary" asp-area="" asp-controller="Home" asp-action="Daftar">Daftar</a>
                            </li>
                        }
                        else
                        {
                            <li class="nav-item ms-auto">
                                <form asp-area="" asp-controller="Home" asp-action="Logout" asp-route-returnUrl="@Context.Request.Path@Context.Request.QueryString">
                                    <button class="nav-link text-light btn btn-primary">Logout</button>
                                </form>
                            </li>
                        }

                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="p-3">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2024 - SI Status Gizi
        </div>
    </footer>

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>

    <!-- Inisisalisasi Chart.JS -->
    <script src="https://cdn.jsdelivr.net/npm/chart.js@4.4.3/dist/chart.umd.min.js"></script>
    <!-- Akhir Inisisalisasi Chart.JS -->
    <!-- Inisisalisasi Owl Carousel -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/OwlCarousel2/2.3.4/owl.carousel.min.js"></script>
    <!-- Akhir Inisisalisasi Chart.JS -->

    <script src="~/lib/datatables/js/jquery.dataTables.min.js" asp-append-version="true"></script>

    @* Responsive *@
    <script src="~/lib/datatables/responsive-2.5.0/js/dataTables.responsive.js"></script>
    <script src="~/lib/datatables/responsive-2.5.0/js/responsive.bootstrap.js"></script>
    <script src="~/lib/datatables/responsive-2.5.0/js/responsive.bootstrap4.js"></script>
    <script src="~/lib/datatables/responsive-2.5.0/js/responsive.dataTables.js"></script>
    <script src="~/lib/datatables/responsive-2.5.0/js/responsive.jqueryui.js"></script>
    @* Responsive *@

    <script type="text/javascript">
        $(
            function () {
                $('table.dataTable').DataTable({
                    responsive: {
                        details: {
                            renderer: $.fn.dataTable.Responsive.renderer.listHiddenNodes()
                        }
                    }
                });
                $('.table').addClass('table-responsive-sm table-striped');
            }
        );
    </script>

    @{
        var globalOptions = new ToastrOptions
        {
            closeButton = true,
            progressBar = true,
            newestOnTop = true,
            preventDuplicates = false,
            timeOut = (int)TimeSpan.FromSeconds(5).TotalMilliseconds,
            extendedTimeOut = (int)TimeSpan.FromSeconds(5).TotalMilliseconds,
            showDuration = (int)TimeSpan.FromSeconds(0.5).TotalMilliseconds,
            hideDuration = (int)TimeSpan.FromSeconds(0.5).TotalMilliseconds,
            showEasing = Easings.Swing,
            hideEasing = Easings.Swing,
            showMethod = AnimationMethods.FadeIn,
            hideMethod = AnimationMethods.FadeOut,
            positionClass = PositionClasses.TopRight,
        };
    }
    <vc:toastr global-options=globalOptions></vc:toastr>

    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>